# Generated by Django 4.0 on 2022-01-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccount',
            name='transaction_type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=255),
        ),
    ]
